[build]
  functions = "functions"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" # Autoriser toutes les origines
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/send-email"
  to = "/.netlify/functions/send-email"
  status = 200
